# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 2%

codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests/"
  - "setup.py"
  - "**/__pycache__/"
  - "*.pyc"
