version: '3.8'

services:
  web:
    environment:
      - FLASK_CONFIG=development
      - FLASK_DEBUG=true
    volumes:
      - .:/app
      - logs:/app/logs
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
