version: '3.8'

services:
  web:
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=debug
      - FLASK_DEBUG=true
      - PORT=5000
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./reports:/app/reports
    command: ["uv", "run", "python", "app.py"]
    ports:
      - "5000:5000"
