# LEGACY WORKFLOW - Replaced by ci.yml
# This workflow is kept for reference but disabled.
# The comprehensive CI/CD pipeline is now in ci.yml
name: Test Legacy (Disabled)

on:
  # Disabled - use ci.yml instead
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"
  UV_VERSION: ">=0.8.11,<0.9.0"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytest-mark: [unit, integration, network, api, slow, smoke]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        show-progress: 'true'

    - name: Install a pep440-specifier-satisfying version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: 'true'
        version: ${{ env.UV_VERSION }}

    - name: Install Python ${{ env.PYTHON_VERSION }}
      run: uv python install ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: uv sync --group dev --group test --group security

    - name: Run ${{ matrix.pytest-mark }} tests with coverage
      run: |
        uv run pytest \
        -m ${{ matrix.pytest-mark }} \
        --tb=short \
        --cov=app \
        --cov-report=xml:reports/coverage/coverage-${{ matrix.pytest-mark }}.xml \
        --cov-report=html:reports/coverage/html \
        --cov-report=term \
        --junitxml=reports/pytest_report.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./reports/coverage/coverage-*.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
